version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./konfigurace:/etc/traefik
    networks:
      - traefik_proxy
      - default
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      #- "5432:5432"
    restart: always

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  default:
    driver: bridge