name: PostgreSQL service example

on: push

jobs:
  # Label of the container job
  postgres-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL on Ubuntu
        run: sudo apt update && sudo apt install -y postgresql

      - name: Start PostgreSQL on Ubuntu
        run: 
          sudo systemctl start postgresql.service
          pg_isready
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm i -g pnpm
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: pnpm install

      - name: Apply migrations
        run: pnpm migrate-test
        env: 
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: pnpm run test
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
